name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup EMSDK (C++-to-WebAssembly compilation)
      uses: mymindstorm/setup-emsdk@v11
    
    - name: Install dependencies
      run: bin/install
      
    - name: Build page
      run: make

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: deploy
        publish_dir: ./build
